version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: tests
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
