# Must define the following environment variables in CircleCI web interface:
#  * TWINE_USERNAME
#  * TWINE_PASSWORD


version: 2.1


executors:
  python:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo


commands:
  build:
    steps:
      - checkout
      - restore_cache:
          key: juriscraper-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install Dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt -r requirements-dev.txt
      - save_cache:
          key: juriscraper-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - venv

  test:
    steps:
      - run:
          name: Run the Test Suite
          command: |
            . venv/bin/activate
            python setup.py test


jobs:
  build-test:
    executor: python
    steps:
      - build
      - test

  deploy:
    executor: python
    steps:
      - build
      - run:
          name: Deploying release package to PyPI
          command: |
            . venv/bin/activate

            echo "{ Verify Git Tag Matches setup.py VERSION }"
            python setup.py verify

            echo "{ Creating Release Packages }"
            python setup.py sdist bdist_wheel

            echo "{ Uploading Release Packages to PyPI }"
            twine upload dist/*


workflows:
  build-test-deploy:
    jobs:
      - build-test
      - deploy:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - build-test