# Must define the following environment variables in CircleCI web interface:
#  * TWINE_USERNAME
#  * TWINE_PASSWORD


version: 2.1


executors:
  python:
    parameters:
      version:
        type: string
        default: "2.7"
    docker:
      - image: circleci/python:<< parameters.version >>
    environment:
      PYTHON_VERSION: << parameters.version >>
    working_directory: ~/repo


commands:
  build:
    steps:
      - checkout
      - restore_cache:
          key: juriscraper-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ .Environment.PYTHON_VERSION }}
      - run:
          name: Install Dependencies
          command: |
            echo "{ Installing dependencies: python $PYTHON_VERSION }"
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt -r requirements-dev.txt
      - save_cache:
          key: juriscraper-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ .Environment.PYTHON_VERSION }}
          paths:
            - venv

  test:
    steps:
      - run:
          name: Run the Test Suite
          command: |
            echo "{ Testing: python $PYTHON_VERSION }"
            . venv/bin/activate
            python setup.py test
jobs:
  build:
    executor: python
    steps:
      - build

  build-test-2.7:
    executor: python
    <<: &build-test
      steps:
        - build
        - test

  build-test-3.5:
    executor: python
      version: "3.5"
    <<: *build-test

  build-test-3.6:
    executor: python
      version: "3.6"
    <<: *build-test

  deploy:
    executor: python
    steps:
      - build
      - run:
          name: Deploying release package to PyPI
          command: |
            . venv/bin/activate
            echo "{ Verify Git Tag Matches setup.py VERSION }"
            python setup.py verify
            echo "{ Creating Release Packages }"
            python setup.py sdist bdist_wheel
            echo "{ Uploading Release Packages to PyPI }"
            twine upload dist/*
workflows:
  version: 2

  untagged:
    jobs:
      - build
      - build-test-2.7: &require-build
          requires:
            - build
      - build-test-3.5: *require-build
      - build-test-3.6: *require-build

  tagged:
    jobs:
      - build: &filter-tags
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - build-test-2.7: &filter-tags-and-require-build
          <<: *filter-tags
          <<: *require-build
      - build-test-3.5: *filter-tags-and-require-build
      - build-test-3.6: *filter-tags-and-require-build
      - deploy:
          <<: *filter-tags
          requires:
            - build-test-2.7
            - build-test-3.5
            - build-test-3.6